name = "Frühling"
license = "MIT"
description = "Theme created for the https://romka.eu blog"
homepage = "https://github.com/romka/fruhling"
tags = ["Blog", "Responsive", "Personal", "Light", "Minimal", "Clean", "Gallery", "Multilingual", "Bootstrap", "Google Analytics"]
features = []
min_version = "0.0.1"

[author]
    name = "Roman Arkharov"
    homepage = "https://romka.eu"

